name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]

    name: run tests
    runs-on: ${{ matrix.platform }}
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: checkout code
        uses: actions/checkout@v2

      - name: run tests
        run: go test -v ./...

      - name: build binaries
        run: go build ./cmd/flow
